### ISSUE TITLE
Download for rpm-based systems

### ISSUE THREAD

**Issue by lebogan** [straight-shoota/md2pdf#1]
I am using Fedora and CentOS for development. Your install only references Ubuntu. Is there a download for rpm-based os's? Thanks.

**Comment by straight-shoota** [comment]
You just need to install `libwkhtmltox`. It usually comes with [`wkhtmltopdf`](https://wkhtmltopdf.org/) which might or might not be available in your distribution sources directly. Otherwise follow the [installations instructions for wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/INSTALL.md).

**Comment by lebogan** [comment]
@straight-shoota , thanks. I finally did find a rpm for the libwkhtmltox at https://fedora.pkgs.org/27/fedora-updates-x86_64/wkhtmltopdf-devel-0.12.4-1.fc27.x86_64.rpm.html. I also needed libxml2-devel, which comes with this distro. m2pdf compiled and works beautifully.

Thanks again.
